# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongo_griffin}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["allen"]
  s.date = %q{2010-10-07}
  s.description = %q{ThingSphinx like API, Sphinx for MongoDB}
  s.email = %q{allen@seravia.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mongo_griffin.rb",
     "lib/mongo_griffin/attribute.rb",
     "lib/mongo_griffin/context.rb",
     "lib/mongo_griffin/core/string.rb",
     "lib/mongo_griffin/field.rb",
     "lib/mongo_griffin/index.rb",
     "lib/mongo_griffin/index_builder.rb",
     "lib/mongo_griffin/mongoid/document_ext.rb",
     "lib/mongo_griffin/xml_pipe2/builder.rb",
     "mongo_griffin.gemspec",
     "test/helper.rb",
     "test/mongo_griffin/core/test_string.rb",
     "test/mongo_griffin/mongoid/test_document_ext.rb",
     "test/mongo_griffin/xml_pipe2/test_builder.rb",
     "test/mongoid.yml",
     "test/test_mongo_griffin.rb"
  ]
  s.homepage = %q{http://github.com/allenwei/mongo_griffin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Sphinx for MongoDB}
  s.test_files = [
    "test/helper.rb",
     "test/mongo_griffin/core/test_string.rb",
     "test/mongo_griffin/mongoid/test_document_ext.rb",
     "test/mongo_griffin/test_configuration.rb",
     "test/mongo_griffin/xml_pipe2/test_builder.rb",
     "test/test_mongo_griffin.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<riddle>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mongoid>, [">= 0"])
      s.add_development_dependency(%q<bson_ext>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
    else
      s.add_dependency(%q<riddle>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mongoid>, [">= 0"])
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
    end
  else
    s.add_dependency(%q<riddle>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mongoid>, [">= 0"])
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
  end
end

